FROM rust:latest
RUN apt-get update && apt-get install -y curl && \
    curl -L https://github.com/rust-lang/rust-analyzer/releases/latest/download/rust-analyzer-x86_64-unknown-linux-gnu.gz | gunzip -c > /usr/local/bin/rust-analyzer && \
    chmod +x /usr/local/bin/rust-analyzer
EXPOSE 8085
CMD ["rust-analyzer", "--server", "--port", "8085"]
